[2022-06-15 16:49:40,636] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v3.third_task manual__2022-06-15T16:49:38.243611+00:00 [queued]>
[2022-06-15 16:49:40,649] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v3.third_task manual__2022-06-15T16:49:38.243611+00:00 [queued]>
[2022-06-15 16:49:40,650] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 16:49:40,650] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-15 16:49:40,651] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 16:49:40,669] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): third_task> on 2022-06-15 16:49:38.243611+00:00
[2022-06-15 16:49:40,679] {standard_task_runner.py:52} INFO - Started process 2640 to run task
[2022-06-15 16:49:40,688] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'third_task', 'manual__2022-06-15T16:49:38.243611+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp7v01wzfr', '--error-file', '/tmp/tmpbcww58j1']
[2022-06-15 16:49:40,691] {standard_task_runner.py:80} INFO - Job 9: Subtask third_task
[2022-06-15 16:49:40,808] {task_command.py:370} INFO - Running <TaskInstance: our_first_dag_v3.third_task manual__2022-06-15T16:49:38.243611+00:00 [running]> on host e2977833d61b
[2022-06-15 16:49:40,961] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=phersonj
AIRFLOW_CTX_DAG_ID=our_first_dag_v3
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-15T16:49:38.243611+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-15T16:49:38.243611+00:00
[2022-06-15 16:49:40,964] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-15 16:49:40,966] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task 3, and will be running after task 1 at the same time as task 2']
[2022-06-15 16:49:40,986] {subprocess.py:85} INFO - Output:
[2022-06-15 16:49:40,997] {subprocess.py:92} INFO - hey, I am task 3, and will be running after task 1 at the same time as task 2
[2022-06-15 16:49:41,001] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-15 16:49:41,075] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=third_task, execution_date=20220615T164938, start_date=20220615T164940, end_date=20220615T164941
[2022-06-15 16:49:41,142] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-15 16:49:41,202] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
