[2022-06-14 16:43:23,909] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-06-14T16:43:22.432043+00:00 [queued]>
[2022-06-14 16:43:23,921] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-06-14T16:43:22.432043+00:00 [queued]>
[2022-06-14 16:43:23,922] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 16:43:23,923] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-14 16:43:23,924] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 16:43:23,942] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): also_run_this> on 2022-06-14 16:43:22.432043+00:00
[2022-06-14 16:43:23,947] {standard_task_runner.py:52} INFO - Started process 2933 to run task
[2022-06-14 16:43:23,953] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2022-06-14T16:43:22.432043+00:00', '--job-id', '10', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpp7yq687o', '--error-file', '/tmp/tmp8v0bhd4r']
[2022-06-14 16:43:23,955] {standard_task_runner.py:80} INFO - Job 10: Subtask also_run_this
[2022-06-14 16:43:24,045] {task_command.py:370} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2022-06-14T16:43:22.432043+00:00 [running]> on host a7436a86ff1e
[2022-06-14 16:43:24,343] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T16:43:22.432043+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-14T16:43:22.432043+00:00
[2022-06-14 16:43:24,345] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-14 16:43:24,348] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2022-06-14T16:43:22.432043+00:00 | dag_run=<DagRun example_bash_operator @ 2022-06-14 16:43:22.432043+00:00: manual__2022-06-14T16:43:22.432043+00:00, externally triggered: True>"']
[2022-06-14 16:43:24,364] {subprocess.py:85} INFO - Output:
[2022-06-14 16:43:24,367] {subprocess.py:92} INFO - run_id=manual__2022-06-14T16:43:22.432043+00:00 | dag_run=<DagRun example_bash_operator @ 2022-06-14 16:43:22.432043+00:00: manual__2022-06-14T16:43:22.432043+00:00, externally triggered: True>
[2022-06-14 16:43:24,368] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-14 16:43:24,416] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20220614T164322, start_date=20220614T164323, end_date=20220614T164324
[2022-06-14 16:43:24,492] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-14 16:43:24,548] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
